name: CI
on:
  workflow_call:

jobs:
  format_lint:
    name: Format and lint
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up
        uses: ./.github/workflows/setup-action

      - name: Format
        run: pnpm run format:ci

      - name: Lint
        run: pnpm run lint:fix

      - name: Commit and push changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: github-actions[bot]
          author_email: github-ations[bot]@users.noreply.github.com
          message: "style: Format code"
